config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments
    end
  end

  resource :profile, only: [ :show, :edit, :update ]
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id           :bigint           not null, primary key
#  birthday     :date
#  gender       :integer
#  introduction :text
#  nickname     :string
#  subscribed   :boolean          default(FALSE)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
    enum gender: { male: 0, female: 1, other: 2 }
    belongs_to :user
    has_one_attached :avatar

    def age
        return '不明' unless birthday.present?
        years = Time.zone.now.year - birthday.year
        days = Time.zone.now.yday - birthday.yday

        if days < 0
            "#{years - 1}歳"
        else
            "#{years}歳"
        end
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    # ログイン必須
    before_action :authenticate_user!

    def show
        @profile = current_user.profile
    end

    def edit
        @profile = current_user.prepare_profile
    end

    def update
        @profile = current_user.prepare_profile
        @profile.assign_attributes(profile_params)
        if @profile.save
            redirect_to profile_path, notice: 'プロフィールを更新'
        else
            flash.now[:error] = '更新できませんでした'
            render :edit, status: :unprocessable_entity
        end
    end

    private
    def profile_params
        params.require(:profile).permit(
            :nickname,
            :introduction,
            :gender,
            :birthday,
            :subscribed,
            :avatar
        )
    end
end

app/views/profiles/edit.html.haml
.form-container
  %h2 Profile Edit
  %ul
    - @profile.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @profile, url: profile_path, method: "put", local: true) do |f|
    .field_spacious
      = f.label :avatar, "Avatar"
      = f.file_field :avatar
    .field_spacious
      = f.label :nickname, "Name"
      = f.text_field :nickname, class: "text"
    .field_spacious
      = f.label :introduction, "Introduction"
      = f.text_area :introduction
    .field_spacious
      = f.label :gender, "Gender"
      = f.select :gender, Profile.genders.map { |k, v| [ I18n.t("enum.genders.#{k}"), k ]}, {}, { class: 'text' }
    .field_spacious
      = f.label :birthday, "Birthday"
      = f.date_field :birthday, class: 'text'
    .field_spacious
      = f.label :subscribed, "Get notifications"
      = f.check_box :subscribed

    = f.submit 'Save', class: 'btn-primary'

app/views/profiles/show.html.haml
.container.profilePage
  %h2 Profile
  .profilePage_user
    .profilePage_user_image
      = image_tag current_user.avatar_image
    .profilePage_user_basicInfo
      .profilePage_user_name
        .profilePage_user_displayName
          = current_user.display_name
      .profilePage_user_introduction
        = current_user.introduction
    .profilePage_user_actionButton
      = link_to 'Edit', edit_profile_path

  - current_user.boards.each do |board|
    = render "commons/board", board: board