config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments
    end
  end

  resource :profile, only: [ :show, :edit, :update ]
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  deadline   :datetime         not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
class Task < ApplicationRecord
    has_many :comments, dependent: :destroy

    has_one_attached :eyecatch

    validates :title, presence: true
    validates :title, length: { minimum: 1, maximum: 100 }

    validates :content, presence: true
    validates :content, length: { minimum: 1, maximum: 500 }

    validates :deadline, presence: true

    belongs_to :user
    belongs_to :board

    def comments_count
        comments.count
    end

    def commenting_users
        comments.includes(:user).map(&:user).uniq
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    # ログイン必須
    before_action :authenticate_user!

    def show
        @task = Task.find(params[:id])
        @comments = @task.comments
    end

    def new
        board = Board.find(params[:board_id])
        @task = board.tasks.build(user: current_user)
    end

    def create
        board = Board.find(params[:board_id])
        @task = board.tasks.build(task_params.merge(user: current_user))
        if @task.save
            redirect_to board_path(board), notice: 'タスクを追加しました'
        else
            flash.now[:error] = '更新できませんでした'
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @task = current_user.tasks.find(params[:id])
    end

    def update
        @task = current_user.tasks.find(params[:id])
        if @task.update(task_params)
            redirect_to board_task_path(@task.board, @task), notice: '更新できました'
        else
            flash.now[:error] = '更新できませんでした'
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        task = current_user.tasks.find(params[:id])
        task.destroy!
        redirect_to board_path(task.board), status: :see_other, notice: '削除に成功しました'
    end

    private
    def task_params
        params.require(:task).permit(:title, :content, :deadline, :eyecatch)
    end
end

app/views/tasks/_form.html.haml
- if task.errors.any?
  %ul.error-messages
    - task.errors.full_messages.each do |message|
      %li= message

= form_with(model: task, url: url, local: true) do |f|
  .field_spacious
    = f.label :title, "Name"
    = f.text_field :title, class: "text"
  .field_spacious
    = f.label :content, "Description"
    = f.text_area :content
  .field_spacious
    = f.label :deadline, "Dead Line"
    = f.datetime_field :deadline, class: "text"
  .field_spacious
    = f.label :eyecatch, "Eyecatch"
    = f.file_field :eyecatch
  = f.submit "Submit", class: "btn-primary"

app/views/tasks/edit.html.haml
.form-container
  %h2 Edit Card
  = render "form", task: @task, url: board_task_path(@task.board, @task)

app/views/tasks/new.html.haml
.form-container
  %h2 New Card
  = render "form", task: @task, url: board_tasks_path(@task.board)

app/views/tasks/show.html.haml
.container
  .task_header
    %h2
      = @task.title
      - if user_signed_in? && current_user.written_by_me?(@task)
        .task_header_actions
          .dropdown
            = image_tag 'actions.svg', class: 'dropbtn'
            .dropdown-content.mini
              = link_to "Edit", edit_board_task_path(@task.board, @task)
              = link_to "Delete", board_task_path(@task.board, @task), data: { turbo_method: "delete", turbo_confirm: "本当に削除してもよろしいですか？" }
  - if @task.eyecatch.attached?
    .task_image
      = image_tag @task.eyecatch
  .task_detail
    .task_deadline
      = "期限：#{l(@task.deadline, format: :long)}"
    .task_content
      = @task.content

  .task-comment
    %div Comment
    - @comments.each do |comment|
      .task-comment-detail
        .task-comment_avatar
          = image_tag comment.user.avatar_image
        .task-comment_content
          = comment.content

    = link_to new_board_task_comment_path(@task.board, @task) do
      .card-add.comment
        .card-add_content
        %span.plus-icon +
        %span.add-text Add new comment