config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments
    end
  end

  resource :profile, only: [ :show, :edit, :update ]
end

app/views/commons/_board.html.haml
.card
  = link_to board_path(board), class: 'card-link' do
    .card_content
      .card_title_row
        .card_title
          = board.title
      .card_description
        = board.description
      .card_bottom
        .card_avatar
          = image_tag board.user.avatar_image

  - if user_signed_in? && current_user.written_by_me?(board)
    .card_actions
      .dropdown
        = image_tag 'actions.svg', class: 'dropbtn-mini'
        .dropdown-content.mini
          = link_to "Edit", edit_board_path(board)
          = link_to "Delete", board_path(board), data: { turbo_method: "delete", turbo_confirm: "本当に削除してもよろしいですか？" }

app/views/commons/_task.html.haml
= link_to board_task_path(task.board, task) do
  .card
    - if task.eyecatch.attached?
      .card_image
        = image_tag task.eyecatch
    .card_content
      .card_title_row
        .card_title
          = task.title
      .card_description
        = task.content
      .card_deadline
        = "期限：#{l(task.deadline, format: :long)}"
      .card_bottom
        .card_avatar
          = image_tag task.user.avatar_image
        - task.commenting_users.each do |commenter|
          .card_avatar.comment-avatar
            = image_tag commenter.avatar_image

        .card_comment_count
          = "#{task.comments_count}"
          = image_tag 'comment_icon.svg'