config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments
    end
  end

  resource :profile, only: [ :show, :edit, :update ]
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id          :bigint           not null, primary key
#  description :text             not null
#  title       :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord
    validates :title, presence: true
    validates :title, length: { minimum: 1, maximum: 100 }
    validates :title, uniqueness: true

    validates :description, presence: true
    validates :description, length: { minimum: 1, maximum: 500 }
    validates :description, uniqueness: true

    has_many :tasks, dependent: :destroy

    belongs_to :user
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    def index
        @boards = Board.all.order(id: :asc)
    end

    def show
        @board = Board.find(params[:id])
        @tasks = @board.tasks
    end

    def new
        @board = current_user.boards.build
    end

    def create
        @board = current_user.boards.build(board_params)
        if @board.save
            redirect_to root_path, notice: '保存できました'
        else
            flash.now[:error] = '保存に失敗しました'
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @board = current_user.boards.find(params[:id])
    end

    def update
        @board = current_user.boards.find(params[:id])
        if @board.update(board_params)
            redirect_to boards_path(@board), notice: '更新できました'
        else
            flash.now[:error] = '更新できませんでした'
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        board = current_user.boards.find(params[:id])
        board.destroy!
        redirect_to root_path, status: :see_other, notice: '削除に成功しました'
    end

    private
    def board_params
        params.require(:board).permit(:title, :description)
    end
end

app/views/boards/_form.html.haml
- if board.errors.any?
  %ul.error-messages
    - board.errors.full_messages.each do |message|
      %li= message

= form_with(model: board, local: true) do |f|
  .field_spacious
    = f.label :title, "Name"
    = f.text_field :title, class: "text"
  .field_spacious
    = f.label :description, "Description"
    = f.text_area :description
  = f.submit "Submit", class: "btn-primary"

app/views/boards/edit.html.haml
.form-container
  %h2 Edit Board
  = render "form", board: @board

app/views/boards/index.html.haml
.container
  %h2 All Boards
  - @boards.each do |board|
    = render "commons/board", board: board

  = link_to new_board_path do
    .card-add
      .card-add_content
      %span.plus-icon +
      %span.add-text Add new board

app/views/boards/new.html.haml
.form-container
  %h2 New Board
  = render "form", board: @board

app/views/boards/show.html.haml
.container
  %h2
    = @board.title
  - @tasks.each do |task|
    = render "commons/task", task: task

  = link_to new_board_task_path(@board.id) do
    .card-add
      .card-add_content
      %span.plus-icon +
      %span.add-text Add new card